version: '3'
services:
  # elasticsearch:
  #     image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
  #     container_name: elasticsearch
  #     networks:
  #       - elk-network
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://artisan.limeleads.com:9200
    ports:
      - "5601:5601"
    # networks:
    #   - elk-network
    # depends_on:
    #     - elasticsearch
# networks:
#   elk-network:
#     driver: bridge